#!/bin/bash

set -eu

if [ "${1:-}" == "--fix" ] ; then
  npm exec -- markdownlint --ignore 'node_modules/' --fix '**/*.md'
  npm exec -- prettier --write .
else
  trap '
    if [ $? -ne 0 ] ; then
      echo "Try '\''./lint --fix'\'' to see if any automatic fixes are possible"
    fi
  ' 0

  rc=0

  echo "validateLinks: ..."
  if npm exec -- node dist/validateLinks.js ; then
    echo validateLinks: PASS
  else
    echo validateLinks: FAIL
    rc=1
  fi

  echo "markdownlint: ..."
  if npm exec -- markdownlint --ignore 'node_modules/' '**/*.md' ; then
    echo "markdownlint: PASS"
  else
    echo "markdownlint: FAIL"
    rc=1
  fi

  echo "prettier: ..."
  if npm exec -- prettier --check . ; then
    echo "prettier: PASS"
  else
    echo "prettier: FAIL"
    rc=1
  fi

  exit $rc
fi
